### ISSUE TITLE
MKL searching is kind of obfuscated

### ISSUE THREAD

**Issue by wavepacket** [juanjosegarciaripoll/tensor#12]
The problem is not so much that tensor is no longer installable on my work computer out of the box using MKL (that too), but the output messages are pretty much pointless. Without digging into the m4 code, it is impossible to make sense of why all mkl files are found, but not the library.

So in the very least, a few more error messages would be useful.

**Comment by juanjosegarciaripoll** [comment]
Fixed in cmake branch
