### ISSUE TITLE
Summation along individual indices

### ISSUE THREAD

**Issue by wavepacket** [juanjosegarciaripoll/tensor#15]
My specific problem: I have a two-dimensional wave function / tensor psi(x,y), and I want to know the weight of certain harmonic oscillator states phi_n(x) and phi_m(y). Doing the math, this involves partial summation over, e.g., only the x-degree of freedom.

Hence, a function that sums a tensor only over some indices would be very handy. Right now, I work around by using the corresponding mean function, but this is ugly.

**Comment by juanjosegarciaripoll** [comment]
The cmake branch now has sum(), mean(), min() and max() as accumulating functions that run over a prescribed index.
