### ISSUE TITLE
Build and Install CXXFLAGS, C compiler cannot create executables.

### ISSUE THREAD

**Issue by rohitmulay** [juanjosegarciaripoll/tensor#19]
I'm facing trouble in Build and Install part the 2nd step. I gave the command `./configure --prefix=$HOME LIBS="-llapack -lcblas -latlas" CXXFLAGS="src/Makefile.inc"` and got the following output
```
    checking for gcc... gcc
    checking whether the C compiler works... no
    configure: error: in `/home/rmulay17/Downloads/tensor-master':
    configure: error: C compiler cannot create executables
    See `config.log' for more details
```

I don't know if this command is correct or wrong because i don't know what to include in **CXXFLAGS="..."** so, someone please guide me how to use ` ./configure --prefix=$HOME LIBS="..." CXXFLAGS="..."` 
I have already installed BLAS and LAPACK. GCC Compiler is also installed and also tired after installing libc6-dev. 

This is what i got after the command `./autogen.sh`
![screenshot from 2017-07-05 09-39-03](https://user-images.githubusercontent.com/29452108/27849677-9151c358-613e-11e7-84d8-7f53288a7408.png)

**Comment by ClmnsRck** [comment]
Did you get it to work eventually? I would like to use this Library, but cant install it

**Comment by juanjosegarciaripoll** [comment]
Apologies for the unfortunate delay. For some reason GitHub never notified me of the issues in this repository. The right way to build the library now is using CMake. This new build system does not enable passing "LIBS" but requires that libraries be available in the system, following good practices (either CMake configuration or pkg-config, both of which are usual in Linux).
