### ISSUE TITLE
to_complex() does not work as expected

### ISSUE THREAD

**Issue by wavepacket** [juanjosegarciaripoll/tensor#20]
In src/tensor/tensor_to_complex.cpp, line 40, the last iterator is not incremented properly ("+ii" instead of "++ii"), which causes the reconstructed complex tensor to be wrong.

Effectively, if you supply the two RTensors, you get a complex tensors with the correct real values, but whose imaginary values are all the first entry of the second tensors.

**Comment by juanjosegarciaripoll** [comment]
Fixed in master and cmake
